replicaCount: 2

image:
  repository: iquyan/dailyops
  tag: v2
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

serviceMonitor:
  enabled: true
  releaseLabel: monitoring
  path: /metrics
  interval: 30s
